version: '2'
services:
  nextbus:
    build: .
    ports:
     - 8080:8080
    volumes:
     - .:/code
    links:
     - redis
     - mongo
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo:latest"
  
